export const SHARE_ERRORS = {
  ANALYSIS_NOT_FOUND: 'ANALYSIS_NOT_FOUND',
  FORBIDDEN: 'SHARE_FORBIDDEN',
  TOKEN_GENERATION_FAILED: 'TOKEN_GENERATION_FAILED',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const

export type ShareErrorCode = typeof SHARE_ERRORS[keyof typeof SHARE_ERRORS]
